[env]
DOCKER_TAG = "latest"

[tasks.build]
description = "Build docker image to deploy"
run = '''
docker build -t budougumi0617/gotodo:${DOCKER_TAG} \
  --target deploy ./
'''

[tasks.build-local]
description = "Build docker image to local development"
run = "docker compose build --no-cache"

[tasks.up]
description = "Do docker compose up with hot reload"
run = "docker compose up -d"

[tasks.down]
description = "Do docker compose down"
run = "docker compose down"

[tasks.logs]
description = "Tail docker compose logs"
run = "docker compose logs -f"

[tasks.ps]
description = "Check container status"
run = "docker compose ps"

[tasks.test]
description = "Execute tests"
# -race:データ競合（data race）を検出する
# -shuffle=on :シャッフルして 順番依存しているバグを見つける
# ./... : 全テストファイルが対象
run = "go test -race -shuffle=on ./..."

[tasks.dev]
description = "ローカル開発サーバー"
run = 'go run .'
